name: tech_app
description: Appliance Repair Technician App (Flutter)
publish_to: 'none'
version: 1.0.1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  geolocator: ^10.1.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  lucide_icons: ^0.1.0
  latlong2: ^0.9.0

  provider: ^6.0.5
  intl: ^0.18.1
  url_launcher: ^6.1.11
  image_picker: ^1.0.4
  signature: ^5.4.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
