name: client_app
description: Appliance Repair Client App (Flutter)
publish_to: 'none'
version: 1.0.1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

  geolocator: ^10.1.0
  provider: ^6.0.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
